---

- name: Learn about hosts to group
  hosts: all
  tasks:
  - name: Classify hosts depending on their OS family
    group_by:
      key: OS_FAMILY_{{ ansible_facts['os_family'] }}

- hosts: OS_FAMILY_Debian
  name: Install prerequisites based on OS
  tasks:
    - apt: name={{ item }} 
      state: present
      with_items:
      - python3
      - python3-pip
      - git

- hosts: OS_FAMILY_Archlinux
  name: Install prerequisites based on OS
  tasks:
    - pacman: name={{ item }} 
      state: present
      with_items:
      - python3
      - python3-pip
      - git

- hosts: OS_FAMILY_RedHat
  name: Install prerequisites based on OS
  tasks:
    - pacman: name={{ item }} 
      state: present
      with_items:
      - python3
      - python3-pip
      - git